"""add save_count and analyzed_by to recipes

Revision ID: 7fd56f8f0d12
Revises: 42b8b48e7a87
Create Date: 2026-02-10 17:04:09.456201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd56f8f0d12'
down_revision: Union[str, Sequence[str], None] = '42b8b48e7a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('save_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('recipes', sa.Column('analyzed_by', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_recipes_analyzed_by_users', 'recipes', 'users', ['analyzed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recipes_analyzed_by_users', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'analyzed_by')
    op.drop_column('recipes', 'save_count')
    # ### end Alembic commands ###
